service: finnegan-forever

provider:
  name: aws
  runtime: python3.6

package:
  include:
    - finnegans-wake-scroll.txt
    - finnegan_forever/**

functions:
  read-finnegan:
    handler: finnegan_forever/delivery/aws/read_finnegan.handler
    environment:
      PASSAGE_SIZE: 40
      READING_EVERY: 4.5
      FINNEGAN_SCROLL_FILEPATH: finnegans-wake-scroll.txt
    events:
      - http:
          path: /passage
          method: get
          cors: true

plugins:
  - serverless-finch

custom:
  client:
    bucketName: finneganforever.com
    distributionFolder: web_client/build
    routingRules:
      - redirect:
          replaceKeyWith: '#!' # Cannot replace with an empty string
        condition:
          httpErrorCodeReturnedEquals: 404
